apiVersion: v1
kind: Service
metadata:
  name: template-index
  labels:
    kubevirt.io: "template-index"
spec:
  ports:
    - port: 18081
      targetPort: 18081
      protocol: TCP
  selector:
    kubevirt.io: template-index

