kind: ServiceAccount
apiVersion: v1
metadata:
  name: template-index
  namespace: kube-system
  labels:
    kubevirt.io: ""
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: template-index
  namespace: kube-system
  labels:
    kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: template:view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: template-index
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: template:view
  namespace: kube-system
  labels:
    kubevirt.io: ""
rules:
  - apiGroups:
      - template.openshift.io
    resources:
      - templates
    verbs:
      - get
      - list
      - watch
