apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: template-index
  namespace: kube-system
  labels:
    kubevirt.io: "template-index"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: |
                  [
                    {
                      "key": "CriticalAddonsOnly",
                      "operator": "Exists"
                    }
                  ]
      labels:
        kubevirt.io: template-index
    spec:
      serviceAccountName: template-index
      containers:
        - name: kubevirt-template-indexer
          image: fromanirh/kubevirt-template-indexer:devel
          imagePullPolicy: IfNotPresent
          command:
              - "kubevirt-template-indexer"
              - "-N"
              - "kube-system"
              - "-p"
              - "18081"
          ports:
            - containerPort: 18081
              name: "template-index"
              protocol: "TCP"
              scheme: HTTP
