apiVersion: v1
kind: Service
metadata:
  name: template-indexer
  labels:
    kubevirt.io: "template-indexer"
spec:
  ports:
    - port: 18081
      targetPort: 18081
      protocol: TCP
  selector:
    kubevirt.io: template-indexer

